In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('redwine.csv')
df=df1.values

In [4]:
X=df[:,0:11]
Y=df[:,11]
print(Y)

[5. 5. 5. ... 6. 5. 6.]


In [6]:
print(X.shape)
print(Y.shape)

(1599, 11)
(1599,)


In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

In [10]:
print(X_train.shape)
print(Y_test.shape)

(1119, 11)
(480,)


In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [18]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(hidden_layer_sizes=(30,30,30),max_iter=1000)

In [19]:
mlp.fit(X_train,Y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(30, 30, 30), learning_rate='constant',
              learning_rate_init=0.001, max_iter=1000, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [20]:
y_pred=mlp.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [22]:
print(confusion_matrix(Y_test,y_pred))

[[  0   0   1   0   0   0]
 [  1   0  11   5   0   0]
 [  1   5 135  49   4   1]
 [  0   1  50 116  29   4]
 [  0   2   0  20  35   4]
 [  0   0   0   1   5   0]]


In [24]:
print(accuracy_score(Y_test,y_pred)*100)

59.583333333333336


In [25]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

         3.0       0.00      0.00      0.00         1
         4.0       0.00      0.00      0.00        17
         5.0       0.69      0.69      0.69       195
         6.0       0.61      0.58      0.59       200
         7.0       0.48      0.57      0.52        61
         8.0       0.00      0.00      0.00         6

    accuracy                           0.60       480
   macro avg       0.30      0.31      0.30       480
weighted avg       0.59      0.60      0.59       480



In [26]:
 print(len(mlp.coefs_))

4


In [27]:
 print(len(mlp.coefs_[0]))

11


In [29]:
 print(mlp.intercepts_[0])

[ 0.10351055 -0.17777432  0.82447785  0.38979908 -0.12957803 -0.06690511
  0.18931955 -0.54412242 -0.47718498 -0.39185172 -0.35090516 -0.28131458
  0.5919776  -0.35138736 -0.23581282  0.22066195 -0.56019149 -0.29160252
 -0.43171516  0.47972903  0.11607288  0.50540722  0.65724561  0.16445459
  0.15336536  0.73090226 -0.25547511  0.29009769 -0.4216446   0.98150254]
